### ISSUE TITLE
Encourage new validators to use a minority client

### ISSUE THREAD

**Issue by hesom** [ethereum/staking-launchpad#427]
Right now [approximately 65% of validators](https://twitter.com/sproulM_/status/1440512518242197516) run Prysm. In my opinion there should be a disclaimer about the importance of client diversity (not only for the network health but also because of the increased financial risk due to inactivity penalties if all Prysm validators went down). Maybe there could even be a warning if the user chooses Prysm

**Comment by paulmillr** [comment]
I think it's very important to emphasize this. Totally agree
