### ISSUE TITLE
Update launchpad instructions & checklist to post-Merge mode

### ISSUE THREAD

**Issue by hwwhww** [ethereum/staking-launchpad#448]
Once we merged EL+CL, the validator will have to run EL clients with engine APIs. It may also have different requirements and set up for validators.

- Checklist: https://launchpad.ethereum.org/en/checklist
	* Update the setup description
	* Update “node security” section for Engine APIs
	* Update “Configure your execution client” section
	* Link to The Merge configuration tutorial
- Deposit workflow
	* Update every EL client intro if needs
	* Edit “You can use a third-party service like Infura, but we recommend running your own client to keep the network as decentralized as possible.”

**Comment by samajammin** [comment]
@wackerow think this can be closed out? I believe this was solved in PRs related to https://github.com/ethereum/staking-launchpad/issues/527 (though I'm not positive).

**Comment by wackerow** [comment]
As far as I can tell everything on here should be addressed at this point. The only thing possibly missing may be the "Merge configuration tutorial" which I'm not sure is really necessary anymore. Participation rate has been ~99%, so I'm comfortable graduating to an environment that is purely post-merge, and we can call The Merge a success. Closing =)

**Comment by samajammin** [comment]
Awesome, thanks!
