### ISSUE TITLE
Feature request: Include statement about slashed funds before Shanghai

### ISSUE THREAD

**Issue by wackerow** [ethereum/staking-launchpad#479]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/54227730/166157374-e3c0e4ec-271f-488f-94e6-6a66776f2a0b.png">

Filing here an issue raised on Discord. The site does currently warn that funds cannot yet be withdrawn, and also warns that slashing will result in forced exiting from the network. Given that, there is a gap here that could be filled still by making sure users realize that any slashed funds will be exited, and locked until the ability to withdraw and transfer funds is enabled via Shanghai. The inability to re-stake these funds until Shanghai could be made more explicit.

**Comment by corwintines** [comment]
I don't think we need this anymore. Unfortunately we ended up with the thumbs-down option I had mentioned, but now that we're ~3 weeks away from Shanghai, with all the other updates that have been done related to withdrawals, I don't think we need to specifically address this anymore. Closing out

Based on linked issue above: https://github.com/ethereum/ethereum-org-website/issues/6193

**Comment by wackerow** [comment]
Yep, Shapella 9 days out... closing this out.
