### ISSUE TITLE
It's still early to prepare for the merge

### ISSUE THREAD

**Issue by remyroy** [ethereum/staking-launchpad#511]
Some instructions on https://launchpad.ethereum.org/en/merge-readiness might need to wait for an actual TTD value to be published or some clients to update with a baked in TTD value for Mainnet before stakers actually apply them on their machine. Phrasing or notices should be added to account for that.

**Comment by hwwhww** [comment]
Hi @remyroy 👋

I was hesitating about it for this reason as well, but I think we could find a balance between (i) providing the readiness now and (ii) letting stakers understand that we still need the last puzzle to solve it.

@remyroy @wackerow what do you think about we add more warnings around "I am running my own EL/CL client"? For example:
- add introduction of TTD and make it clear that mainnet TTD is unset
- invalidate the checkbox for now?
