### ISSUE TITLE
Redirect the prater launchpad to the goerli launchpad

### ISSUE THREAD

**Issue by remyroy** [ethereum/staking-launchpad#533]
Can we have https://prater.launchpad.ethereum.org/ redirect to https://goerli.launchpad.ethereum.org/ please? It would be such a better experience than the current 403 forbidden error. There are still a bunch of guides and documents pointing to https://prater.launchpad.ethereum.org/. Users should not be greeted with that 403 error.

**Comment by hwwhww** [comment]
Hey @remyroy thanks for the report!

This plan was adding redirection but it seems something went wrong. I've reported to our DNS admin to fix it ASAP.

**Comment by hwwhww** [comment]
https://prater.launchpad.ethereum.org/ now redirects to https://goerli.launchpad.ethereum.org/
Sorry for the inconvenience. 🙏
