### ISSUE TITLE
Hidden continue button on wide resolutions, cannot complete a deposit on connect wallet step

### ISSUE THREAD

**Issue by remyroy** [ethereum/staking-launchpad#659]
Using MetaMask on the dev branch, I cannot complete a deposit on a network configured for Holesky. This issue is currently affecting the main Holesky launchpad on https://holesky.launchpad.ethereum.org/.

After connecting my wallet, I'm left on a page without further possible action to perform:

![Screenshot from 2023-10-03 11-19-26](https://github.com/ethereum/staking-launchpad/assets/303593/a78a7cda-2b61-457f-9e33-6f3a85c85d19)

Resizing my browser window down to about 850 pixels or less makes the continue button show up:

![Screenshot from 2023-10-03 11-29-18](https://github.com/ethereum/staking-launchpad/assets/303593/2cacce2c-17eb-47e1-a5d9-625d8a268ba6)

**Comment by hwwhww** [comment]
Hey @wackerow could you help with it? 🙏

**Comment by catwith1hat** [comment]
I am seeing the same issue. 

The source for the broken page segment is [here](https://github.com/ethereum/staking-launchpad/blob/2ff72b8f876db66e73d44b30e37db0190752f313/src/pages/ConnectWallet/index.tsx#L528-L558) inside `src/pages/ConnectWallet/index.tsx`. The broken buttons are wrapped inside a `ButtonRow`, which has the following in its [definition](https://github.com/ethereum/staking-launchpad/blob/2ff72b8f876db66e73d44b30e37db0190752f313/src/pages/ConnectWallet/index.tsx#L127-L137):
```
@media only screen and (max-width: ${p => p.theme.screenSizes.large}) { ... }
```
This to me reads suspiciously like a conditional that might suppress displaying those buttons on large screen sizes. But OTOH, there are similar definitions inside that file, so I am just guessing.

**Comment by dappnodedev** [comment]
Resizing the browser did the trick to me too!

**Comment by wackerow** [comment]
This is related to some absolute positioning, leaving the ButtonRow stuck behind the other div.... patch incoming.
